services:
  postgres:
    image: postgres:16
    container_name: orders_postgres
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - orders_pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: orders_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  orders_pgdata:
